name: CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

  release:
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Release
        run: cargo build --release

      - name: Create Release Package
        run: |
          mkdir -p release
          cp target/release/web-load-tester release/
          cp -r static release/
          cp README.md release/
          cp LICENSE release/
          tar -czf web-load-tester-ubuntu.tar.gz -C release .

      - name: Create Windows Package
        run: |
          mkdir -p release-win
          cp target/release/web-load-tester.exe release-win/
          cp -r static release-win/
          cp README.md release-win/
          cp LICENSE release-win/
          zip -r web-load-tester-windows.zip release-win/

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            web-load-tester-ubuntu.tar.gz
            web-load-tester-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 