name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: web-load-tester-ubuntu
            file_extension: .tar.gz
          - os: windows-latest
            artifact_name: web-load-tester-windows
            file_extension: .zip

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --release

      - name: Create Release Package
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir -p release
          cp target/release/web-load-tester release/
          cp -r static release/
          cp README.md release/
          cp LICENSE release/
          tar -czf ${{ matrix.artifact_name }}${{ matrix.file_extension }} -C release .

      - name: Create Windows Package
        if: matrix.os == 'windows-latest'
        run: |
          mkdir release
          copy target\release\web-load-tester.exe release\
          xcopy /E /I static release\static
          copy README.md release\
          copy LICENSE release\
          7z a ${{ matrix.artifact_name }}${{ matrix.file_extension }} .\release\*

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ matrix.artifact_name }}${{ matrix.file_extension }}
          asset_name: ${{ matrix.artifact_name }}${{ matrix.file_extension }}
          asset_content_type: application/octet-stream 